seed: 42

data:
  labels_csv: data/labels.csv
  images_dir: data/images

training:
  max_samples: 2000
  batch_size: 32
  img_size: 192
  val_split: 0.2
  epochs: 3
  lr: 0.001

  lr_scheduler:
    type: reduce_on_plateau     # currently only this is implemented
    factor: 0.5
    patience: 1

  early_stopping:
    patience: 2                # stop after 2 epochs without val improvement

models:
  resnet18:
    name: resnet18_finetuned
    version: v1

  efficientnet_b0:
    name: efficientnet_b0_finetuned
    version: v1

  custom_cnn:
    name: custom_cnn
    version: v1

artifacts:
  base_dir: app/models/saved
